workspaceDependencies {
	siblingMaven('HudRendererLib') {
		coordinate.set("io.github.brainage04:hudrendererlib:${rootProject.hudrendererlib_version}")
		siblingDirectory.set(rootProject.layout.projectDirectory.dir('../HudRendererLib'))
	}
}

fabricApi { configureDataGeneration { client = true; modId = rootProject.mod_id } }

dependencies {
	implementation("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") { exclude(group: 'net.fabricmc.fabric-api') }
	productionRuntimeMods("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") { exclude(group: 'net.fabricmc.fabric-api') }
	if (providers.gradleProperty('use_local_hudrendererlib').map { it.toBoolean() }.getOrElse(false)) {
		implementation "io.github.brainage04:hudrendererlib:${project.hudrendererlib_version}"
		productionRuntimeMods "io.github.brainage04:hudrendererlib:${project.hudrendererlib_version}"
	} else {
		implementation "github.brainage04:hudrendererlib:${project.hudrendererlib_version}"
		productionRuntimeMods "github.brainage04:hudrendererlib:${project.hudrendererlib_version}"
	}
	implementation "maven.modrinth:modmenu:${project.modmenu_version}"
}
