modLoader="javafml"
loaderVersion="[11,)"
license="MIT"

[[mods]]
modId="brainagehud"
version="${version}"
displayName="BrainageHUD"
description="A mod that adds useful HUD elements to Minecraft."
logoFile="assets/brainagehud/icon.png"

[[mixins]]
config="brainagehud.client.mixins.json"

[[dependencies.brainagehud]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.brainagehud]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"

[[dependencies.brainagehud]]
modId="cloth_config"
type="required"
versionRange="[${cloth_config_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.brainagehud]]
modId="hudrendererlib"
type="required"
versionRange="[${hudrendererlib_version},)"
ordering="AFTER"
side="CLIENT"
